# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: abnmt.theaterpress::lang.post.label

# Model Form Field configuration
form: $/abnmt/theaterpress/models/post/fields.yaml

# Model Class name
modelClass: Abnmt\TheaterPress\Models\Article

# Default redirect location
defaultRedirect: abnmt/theaterpress/articles

# Create page
create:
    title: abnmt.theaterpress::lang.post.create_title
    redirect: abnmt/theaterpress/articles/update/:id
    redirectClose: abnmt/theaterpress/articles

# Update page
update:
    title: abnmt.theaterpress::lang.post.update_title
    redirect: abnmt/theaterpress/articles
    redirectClose: abnmt/theaterpress/articles

# Preview page
preview:
    title: abnmt.theaterpress::lang.post.preview_title